/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sandersgutierrez.tiendaenlinea;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(new App().getGreeting(), "app should have a greeting");
    }
}
